import { renderToStaticMarkup } from "react-dom/server";
import { createElement } from "react";
import { readFileSync, writeFileSync } from "node:fs";
import { chromium } from "@playwright/test";
const [, , modPath, specJson, out] = process.argv;
import * as React from "react";
(globalThis as any).React = React;
(async () => {
  const mod = await import(modPath);
  const reg = mod.registry as Record<string, any>;
  const spec: [string, any][] = JSON.parse(specJson);
  const css = readFileSync("app/globals.css", "utf8");
  const kcss = readFileSync("node_modules/katex/dist/katex.min.css", "utf8");
  const body = spec.map(([k, p]) => `<div style="border:1px solid #ccc;margin:8px;padding:8px;width:374px"><div style="font:12px sans-serif">${k} ${JSON.stringify(p)}</div>${renderToStaticMarkup(createElement(reg[k], p))}</div>`).join("");
  const html = `<html><head><style>${kcss}</style><style>${css}</style></head><body style="display:flex;flex-wrap:wrap">${body}</body></html>`;
  const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/" + require("node:fs").readdirSync("/opt/pw-browsers").find((d: string) => d.startsWith("chromium-")) + "/chrome-linux/chrome", args: ["--no-sandbox"] });
  const page = await browser.newPage({ viewport: { width: 1200, height: 800 } });
  await page.setContent(html);
  await page.screenshot({ path: out, fullPage: true });
  await browser.close();
})();
