import type { LessonBlock } from "./types";

const h = (text: string): LessonBlock => ({ kind: "heading", text });
const p = (text: string): LessonBlock => ({ kind: "p", text });
const m = (tex: string, key = false): LessonBlock => ({ kind: "math", tex, ...(key ? { key } : {}) });
const a = (tone: "tip" | "watch" | "gre", title: string, text: string): LessonBlock => ({ kind: "aside", tone, title, text });

export const conventions: { title: string; summary: string; lesson: LessonBlock[] } = {
  title: "Math Conventions",
  summary:
    "The unwritten rules of the GRE Quantitative Reasoning measure: what numbers, symbols, figures and graphs mean before any question starts. Page references are to the ETS Math Conventions (MC).",
  lesson: [
    p(String.raw`The GRE uses ordinary high-school notation, and whenever a question needs anything unusual it defines it on the spot. Everything else rests on a handful of standing assumptions. You already know the mathematics; this page is about the **English conventions** that decide what a sentence or a picture is allowed to mean (MC p. 3).`),

    h("Numbers and Quantities"),
    p(String.raw`Every number and every quantity on the test is a **real number**: integers, rational and irrational numbers are all in play, but imaginary numbers never are. Quantities may carry units, but they are still real numbers (MC p. 4). Numbers are written in base 10 with the digits 0 through 9, a period for the decimal point, and commas separating groups of three digits once a number reaches 1,000.`),
    p(String.raw`When an integer is described by its number of digits, you count the ones digit and everything to its left, starting from the leftmost non-zero digit. So 5,000 is a four-digit integer, while 031 is not a three-digit integer (MC p. 4). A few words have fixed meanings: one **billion** is $10^9$ (not $10^{12}$ as in some countries), one dozen is 12, and $\pi$ is the circumference-to-diameter ratio, about 3.14.`),
    a("watch", "Billion", String.raw`In Turkish, _milyar_ is $10^9$, which matches the GRE. The GRE states this explicitly because some countries use "billion" for $10^{12}$; never let that habit change a power of ten.`),
    p(String.raw`**Rounding** has a tie-breaking rule. A positive number exactly halfway between the two candidates goes to the greater one: 23.5 rounds to 24 and 123.985 rounded to the nearest 0.01 is 123.99. A negative number exactly halfway goes to the lesser one, so $-23.5$ rounds to $-24$ (MC p. 4).`),
    a("tip", "Rounding negatives", String.raw`Think "ties go away from zero." For $-7.5$ to the nearest integer the answer is $-8$, not $-7$. In practice ties are rare, because questions usually state the rounding they want.`),
    p(String.raw`**Repeating decimals** are written with a bar over the repeating block, as in $\frac{25}{12} = 2.08\overline{3}$ and $\frac17 = 0.\overline{142857}$ (MC p. 4).`),
    p(String.raw`The words **factor**, **divisor** and **divisible** are used only for integers. If $r$, $s$, $t$ are integers and $rs = t$, then $r$ and $s$ are factors (divisors) of $t$, and $t$ is a multiple of both and divisible by both. Factors of an integer include negative ones: the integer 4 has six factors, $-4,-2,-1,1,2,4$ (MC pp. 4–5). The word **multiple** is more relaxed: it works for any real numbers as long as the multiplier is an integer. So 1.2 is a multiple of 0.4, and $-2\pi$ is a multiple of $\pi$.`),
    m(String.raw`rs = t \quad (r,s,t \text{ integers}) \;\Longrightarrow\; r,s \text{ are factors of } t,\; t \text{ is a multiple of } r,s`, true),
    p(String.raw`The **least common multiple** of two nonzero integers is the least positive integer that is a multiple of both; the **greatest common divisor** (greatest common factor) is the greatest positive integer dividing both (MC p. 5).`),
    p(String.raw`In **division with remainder**, dividing an integer $n$ by a nonzero integer $d$ gives a quotient $q$ and a remainder $r$ with $n = qd + r$ and $0 \le r < |d|$. The remainder is zero exactly when $n$ is a multiple of $d$ (MC p. 5). For example, 20 divided by 6 has quotient 3 and remainder 2, and 21 divided by 7 has quotient 3 and remainder 0.`),
    m(String.raw`n = qd + r, \qquad 0 \le r < |d|`, true),
    p(String.raw`A **prime** is an integer greater than 1 whose only positive divisors are 1 and itself: 2, 3, 5, 7, 11. A **composite** is an integer greater than 1 that is not prime: 4, 6, 8, 9, 10. Neither 1 nor 0 is prime or composite (MC p. 5). Odd and even integers need not be positive: $-3$ is odd, and $-18$ and $0$ are even. And 0 is neither positive nor negative.`),
    a("watch", "Small traps", String.raw`2 is prime and even. 1 is not prime. "Positive integer" excludes 0; "nonnegative integer" includes it. Odd/even says nothing about sign.`),

    h("Mathematical Expressions, Symbols, and Variables"),
    p(String.raw`Italic letters stand for numbers, constants and variables; letters also label objects such as line $\ell$, point $P$, function $f$, set $S$, list $T$, event $E$, random variable $X$, or "Company Z." Context decides which (MC p. 5). Unless restricted, a variable ranges over **all real numbers**. Typical restrictions are "$n$ is a nonzero integer," "$1 < x \le \pi$," or "$T$ is the tens digit of a two-digit positive integer" (so $T$ is an integer from 1 to 9) (MC pp. 5–6).`),
    p(String.raw`Multiplication is usually written by juxtaposition ($2y$, $(3)(4.5)$), division with a fraction bar, and mixed numbers like $4\frac38 = \frac{35}{8}$ appear. Exponent facts: $2^{10}=1{,}024$, $10^{-2}=\frac1{100}$, and $x^0=1$ for every nonzero $x$ (MC p. 6). **Order of operations** is: parentheses, exponentiation, negation, multiplication and division (left to right), addition and subtraction (left to right). Hence $1+2\cdot4 = 9$, and because exponentiation beats negation, $-3^2 = -9$ while $(-3)^2 = 9$ (MC p. 6).`),
    m(String.raw`\text{parentheses} \to \text{exponents} \to \text{negation} \to \times,\div \to +,-`, true),
    a("watch", "Negation versus squaring", String.raw`In $-x^2$ the square is taken first. If $x=-4$, then $-x^2 = -16$, but $(-x)^2 = 16$. This is a favourite quantitative-comparison trap.`),
    p(String.raw`Standard symbols: $\le$, $\ne$, $\approx$, $|x|$ for absolute value, $n!$ with the special definition $0! = 1$, $k \parallel m$ for parallel lines, $k \perp m$ for perpendicular lines, and $\angle B$ for angle $B$. Two radicals matter: $\sqrt{x}$ is the **nonnegative** square root of $x\ge 0$, and $-\sqrt{x}$ is the negative one (MC pp. 6–7). So $\sqrt{25}=5$ only; the equation $x^2=25$ has two solutions, but the symbol $\sqrt{25}$ has one value.`),
    m(String.raw`\sqrt{x^2} = |x| \qquad (\text{not } x)`, true),
    p(String.raw`Since everything is real, some expressions are **undefined**: $x/0$ for every $x$, $\sqrt{x}$ when $x<0$, and $0^0$ (MC p. 7).`),
    p(String.raw`Questions sometimes **define a special operation**, for example "the operation $\ast$ is defined for all integers $r$ and $s$ by $r \ast s = \frac{rs}{1+r^2}$." Treat it as a recipe: substitute and compute. Do not import properties such as commutativity unless you check them; $2\ast 3 \ne 3 \ast 2$ here (MC p. 7).`),
    p(String.raw`Juxtaposition of letters is **not always multiplication**. In "a three-digit positive integer $BCD$, where $B$, $C$, $D$ are digits," $BCD$ means $100B+10C+D$, not $B\cdot C\cdot D$. Context decides (MC p. 7).`),
    m(String.raw`\overline{BCD}\;\text{as digits} = 100B + 10C + D`, true),
    p(String.raw`**Functions** use standard notation. If no domain is given, the domain is the set of all real numbers $x$ for which $f(x)$ is a real number; for $f(x)=\frac{1}{\sqrt{x-3}}$ that means $x>3$. A domain can also be stated, as in "$g$ is defined for all $x \ge 2$ by $g(x)=\frac1{2x}$." The **composition** of $g$ with $f$ is written $g(f(x))$ or $(g\circ f)(x)$: apply $f$ first (MC p. 7).`),
    a("tip", "Composition order", String.raw`Work from the inside out. If $f(x)=x+1$ and $g(x)=x^2$, then $g(f(2)) = 9$ but $f(g(2)) = 5$.`),

    h("Geometry and Geometric Figures"),
    p(String.raw`Ordinary plane (Euclidean) geometry applies, so the angles of a triangle sum to $180^\circ$. Lines are straight and extend forever in both directions. Angle measures are in degrees and are positive and at most $360^\circ$ (MC p. 8).`),
    p(String.raw`When a square, circle, polygon or other closed figure is described in words but not shown, it is assumed to enclose a **convex** region and not to be degenerate (not a single point or a segment). So a "quadrilateral" cannot be a dented, arrowhead shape or a flattened sliver (MC p. 8). "Area of a rectangle" means the area of the region it encloses; likewise for circles and triangles (MC p. 8). The word **similar** means "same shape"; see the Math Review for similar and congruent.`),
    p(String.raw`The **distance from a point to a line** is the length of the perpendicular segment from the point to the line; it is the shortest distance. The distance between two parallel lines is the distance from a point on one to the other line (MC p. 8).`),
    p(String.raw`Points, lines and angles shown as distinct are distinct. All figures lie in a plane unless stated. If $A$, $B$, $C$ are not collinear, segments $AB$ and $BC$ make two angles at $B$, one below $180^\circ$ and one above. Unless said otherwise, **angle $ABC$ is the smaller one** (MC pp. 8–9). The notation $AB$ may mean the segment, its length, or the line through $A$ and $B$; context decides.`),
    { kind: "diagram", diagram: { key: "conventions/AngleABC", caption: String.raw`Angle $ABC$ is the smaller angle at $B$ (solid arc). The dashed arc is the larger angle, which is not meant.` } },
    h("Figures are not drawn to scale"),
    p(String.raw`This is the single most important convention. Geometric figures are **not necessarily drawn to scale**: do not trust lengths or angle sizes as they look. But the figure's *structure* is reliable: lines drawn straight are straight, curves are not straight, points on a line or curve are in the order shown, points on opposite sides of a line really are, and objects are in the relative positions shown. Answer by geometric reasoning, never by eyeballing or measuring (MC p. 9).`),
    { kind: "diagram", diagram: { key: "conventions/NotToScale", caption: String.raw`Note: Figure not drawn to scale. The right angle at $Q$ and $QS = 5$ are marked.` } },
    p(String.raw`In the figure above you **can** assume: $P$, $Q$, $R$ are distinct, $S$ lies between $Q$ and $R$ on a straight segment, $PQS$, $PSR$ and $PQR$ are triangles, angle $PQR$ is a right angle (the small square), and $QS = 5$. You **cannot** assume: that $PQ = QS$ even though they look about equal, that $S$ is the midpoint of $QR$, that angle $PSR$ is a right angle, that $PS$ bisects anything, or that $SR > QS$ merely because it is drawn longer. Those are things "consistent with the way the figure is drawn" but not guaranteed (MC pp. 9–10).`),
    a("gre", "What is given?", String.raw`Ask of every statement: is it a marking (square, label, number), a position (order, betweenness, sides), or only a look? Only the first two are facts. Appearance of equal sides, equal angles, right angles, midpoints, or relative size is not.`),
    a("watch", "Quantitative comparisons", String.raw`If a comparison could flip by redrawing the figure with the same marked data, the answer is often D. Try drawing the figure two ways before trusting the picture.`),

    h("Coordinate Systems"),
    p(String.raw`Unlike geometric figures, **coordinate systems are drawn to scale**: in an $xy$-plane or on a number line you may read, estimate, and compare by sight or measurement, including the shapes drawn inside them (MC p. 11). Horizontal number lines are positive to the right and vertical ones positive upward. Distances are nonnegative.`),
    p(String.raw`The $xy$-plane (rectangular coordinate plane) has a horizontal $x$-axis, positive to the right, and a vertical $y$-axis, positive upward, with equal units on both axes unless noted. The axes meet at the origin $O$ and divide the plane into four **quadrants**. The point $(2,-8)$ lies 2 units right of the $y$-axis and 8 below the $x$-axis, in quadrant IV (MC p. 11–12). Grid lines and tick marks are evenly spaced unless noted.`),
    p(String.raw`The **$x$-intercept** is the $x$-coordinate of the point where a graph meets the $x$-axis; the $y$-intercept is analogous. Sometimes the words name the intersection point itself (MC p. 12). So for $y = 2x-6$ the $x$-intercept is 3 (or the point $(3,0)$) and the $y$-intercept is $-6$.`),
    a("tip", "Two kinds of picture", String.raw`Coordinate planes and data graphs: measure freely. Free-standing geometric figures: reason, don't measure. If a geometric figure sits inside a coordinate plane, it is drawn to scale.`),

    h("Sets, Lists, and Sequences"),
    p(String.raw`A **set** is written in curly brackets. Repeats do not count as extra elements and order does not matter, so $\{2,4,4,6\}=\{6,4,2\}$ has three elements. The empty set $\varnothing$ has no members and is a subset of every set; $A\cap B$ is the intersection, $A\cup B$ the union, and sets with no common element are disjoint (mutually exclusive) (MC pp. 12–13).`),
    p(String.raw`A **list**, in contrast, counts repetitions and cares about order: the list $3,1,2,3,3$ has five numbers, and the first, fourth and fifth are all 3. A "data set" or "set of data" is really a list in this sense, because repeated values matter (MC p. 13). A **sequence** is a list, finite or infinite, with terms $a_1, a_2, a_3,\dots$. Ellipsis dots at the end mean no last term; the $n$th term may be given by a formula such as $b_n = 2n-1$, or by listing initial terms such as $-2,-4,-6,\dots$ (MC p. 13).`),
    p(String.raw`Consecutive integers are described by endpoints: "the integers from 0 to 9" means **10 integers**, with or without the word "inclusive"; likewise "the years from 1985 to 2005" is 21 years (MC p. 13).`),
    m(String.raw`\#\{\text{integers from } a \text{ to } b\} = b - a + 1`, true),
    a("watch", "Fence-post count", String.raw`"From 12 to 40" is 29 integers, not 28. The difference $b-a$ counts gaps, not posts.`),

    h("Data and Statistics"),
    p(String.raw`Questions use measures of **central tendency** (mean, median, mode), **position** (quartiles, percentiles) and **dispersion** (standard deviation, range, interquartile range), and data may be shown in lists, tables, bar graphs or circle graphs (MC p. 13).`),
    p(String.raw`The **average (arithmetic mean)** of a list is the sum divided by the number of entries. On the GRE "average" never means median or mode. Without the parenthetical, "average" may be a rate or ratio, such as "average miles per hour" or "average weight per truckload"; for a finite list, "mean" means arithmetic mean unless noted (MC pp. 13–14).`),
    m(String.raw`\text{mean} = \dfrac{\text{sum of the data}}{\text{number of data}}`, true),
    p(String.raw`The **median** is the middle value of the sorted data for an odd count, or the mean of the two middle values for an even count. The **mode** is the most frequent value, and a list can have more than one mode (MC p. 14). For the list $3,5,5,9,12,14$ the median is $(5+9)/2=7$ and the mode is 5.`),
    p(String.raw`**Quartiles** divide sorted data into four roughly equal groups: the first quartile $Q_1$, the second quartile $Q_2$ (which is the median) and the third quartile $Q_3$. "In the third quartile" refers to the group between $Q_2$ and $Q_3$. **Percentiles** are 99 cut points forming 100 roughly equal groups, with the 25th, 50th and 75th percentiles equal to $Q_1$, $Q_2$, $Q_3$ (MC p. 14).`),
    p(String.raw`With mean $m$, the **standard deviation** is the nonnegative square root of the mean of the squared differences from $m$. This divides by the number of data, so it is the _population_ standard deviation, not the sample one. A larger value means more spread about the mean (MC p. 14). The **range** is greatest minus least; the **interquartile range** is $Q_3 - Q_1$ (MC p. 14).`),
    m(String.raw`\sigma = \sqrt{\dfrac{(x_1-m)^2+\cdots+(x_n-m)^2}{n}}, \qquad \text{range} = \max-\min, \qquad \text{IQR} = Q_3 - Q_1`, true),
    a("gre", "Compare, don't compute", String.raw`Most GRE standard-deviation questions ask only which list is more spread out. Compare distances from the mean; no square roots needed.`),

    h("Data Distributions and Probability Distributions"),
    p(String.raw`A **frequency distribution** records how often each value, or each preset interval of values, occurs; the frequencies add up to the total number of data. Dividing every frequency by that total gives the **relative frequency distribution**, whose entries add to 1 (MC p. 14).`),
    p(String.raw`In a **random selection** or random sample, all samples of equal size are equally likely unless told otherwise. In a random experiment with finitely many outcomes, any set of outcomes is an **event** with probability $P(E)$, where $0\le P(E)\le1$. If all outcomes are equally likely, $P(E)$ is the number of outcomes in $E$ over the number of possible outcomes (MC p. 15). The event "$E$ and $F$" is the intersection and "$E$ or $F$" is the union. Mutually exclusive events have $P(E \text{ and } F)=0$, and events are **independent** exactly when $P(E\text{ and }F)=P(E)P(F)$ (MC p. 15).`),
    m(String.raw`P(E)=\dfrac{\text{outcomes in } E}{\text{all outcomes}}, \qquad P(E \text{ and } F)=P(E)P(F)\ \text{(independent)}`, true),
    p(String.raw`A **random variable** assigns numbers to the results of an experiment. It is **discrete** when it takes finitely many values and **continuous** when its values fill an interval. For a discrete variable, the table or histogram of values $X$ with probabilities $P(X)$ is its probability distribution, and its mean (expected value) is the sum of the products $X\cdot P(X)$ over all values (MC p. 15).`),
    m(String.raw`\text{mean of } X = \sum X\cdot P(X)`, true),
    p(String.raw`For a continuous variable the distribution is a curve $y=f(x)$ with $f\ge0$; the probability of $a<X<b$ is the **area** under the curve, above the $x$-axis, between $x=a$ and $x=b$, and the total area is 1. The mean is the balance point of that region and the median $M$ is where a vertical line cuts the area in half. The standard deviation measures spread about the mean: wider curve, larger standard deviation (MC pp. 15–16).`),
    p(String.raw`The **normal distribution** is bell-shaped and symmetric about $x=m$, which is both mean and median; its tails approach the $x$-axis without touching it. The **standard normal distribution** has mean 0 and standard deviation 1; the MC figure gives approximate probabilities for six intervals, which you read from the figure when a question shows one (MC p. 16).`),
    a("watch", "Areas are probabilities", String.raw`On a density curve the height is not the probability; only area is. By symmetry a normal curve puts exactly half its area on each side of the mean.`),

    h("Graphical Representations of Data"),
    p(String.raw`Bar graphs, circle graphs and line graphs are **drawn to scale**, so you may read, estimate and compare by sight or measurement (MC p. 16). Scales, grid lines, dots, bars, shadings, solid and dashed lines and legends carry the information. Axes may not start at 0, and scales may be broken, so look at the axis before judging how large a difference is. A circle graph represents 100 percent of the data named in its title, with sector areas proportional to the percents (MC p. 16).`),
    p(String.raw`In a **Venn diagram** the circular regions are sets, overlaps are intersections, and an enclosing rectangle, if present, is the universal set. A number inside a region counts the elements of the smallest region containing it, unless noted. A number written above a circle counts the whole set (MC p. 17).`),
    a("tip", "Venn bookkeeping", String.raw`If the numbers sit in the smallest regions, the full size of a circle is the sum of every region inside it. A number placed above the circle is already that total.`),

    h("Miscellaneous Guidelines"),
    p(String.raw`These rules govern how to use the information a question gives (MC pp. 17–18). Read them as ground rules for fair play.`),
    p(String.raw`**Given numbers are exact.** If 30 percent of a profit came from one product, use exactly 30, not a rounded stand-in such as 29 or 30.1. **Counts are totals.** In "a bag contains 50 marbles, and 23 are red," 50 is the whole bag and the other 27 are not red; likewise "one-fifth of the 50 marbles are green" means exactly 10 green and 40 not green (MC p. 17).`),
    p(String.raw`**Approximate answers**: if a multiple-choice question asks for an approximate value with no stated precision, choose the answer closest to the value computed from the given data. **Difference** between two quantities means the _positive_ difference (greater minus lesser) unless otherwise indicated, so "in which two years was the difference in rainfall least" means the absolute value. **Profit** means gross profit, sales revenue minus cost of production or acquisition, with nothing else included unless given (MC p. 17).`),
    p(String.raw`Everyday words (months, years, and so on) have their usual meaning. In real-life settings, a variable standing for a number of objects or an amount of money is **greater than 0** unless noted: if Jane sold $x$ rugs and deposited a profit of $y$ dollars, then $x>0$ and $y>0$ (MC pp. 17–18). Quantities may have any units, but when a conversion is needed the question supplies it unless it is a common one such as minutes and hours, dollars and cents, or centimeters and meters (MC p. 18).`),
    p(String.raw`**Some information may be unnecessary**, so do not hunt for a use for every number. At the same time, do not add assumptions: ignore sales tax, time zones and daylight saving unless mentioned (MC p. 18).`),
    p(String.raw`In **Data Interpretation sets**, every question uses the same display, which may include several graphs or tables, and some data may go unused. Treat each question separately: nothing but the display itself carries over from one question to the next (MC p. 18).`),
    p(String.raw`Finally, when words and symbols mix, **interpret the mathematical expression first, separately from the words**. If $n$ is an integer, "the sum of the first two consecutive integers greater than $n+6$" means $(n+7)+(n+8)$, not "the first two integers greater than $n$, plus 6," which would be $(n+1)+(n+2)+6$. A phrase like "for all $x>0$" is shorthand for "for all numbers $x$ such that $x>0$" (MC p. 18).`),
    m(String.raw`\text{first two integers greater than } n+6 \;\to\; (n+7)+(n+8)`, true),

    a("tip", "Quick checklist before test day", String.raw`Everything is real. Billion is $10^9$. Ties round up for positives, down for negatives. Factors are integers (including negatives); multiples may be real. Remainder satisfies $0\le r<|d|$. 2 is the only even prime; 0 is even and neither positive nor negative. $\sqrt{x}\ge0$; $-3^2=-9$; $0^0$ and $x/0$ are undefined. Letters side by side like $BCD$ may be digits. Angle $ABC$ is the smaller angle. Figures are not to scale: trust markings and order, not looks. Coordinate planes and graphs are to scale. "From $a$ to $b$" has $b-a+1$ integers. Average means mean, not median. Standard deviation is the population version. Given numbers are exact, counts are totals, differences are positive, and variables for real-life counts are positive.`),
  ],
};
