// Generated by scripts/register.ts — do not edit by hand.
import type { ComponentType } from "react";
import { registry as s_1_1_integers } from "./1-1-integers";
import { registry as s_1_2_fractions } from "./1-2-fractions";
import { registry as s_1_3_exponents_and_roots } from "./1-3-exponents-and-roots";
import { registry as s_1_4_decimals } from "./1-4-decimals";
import { registry as s_1_5_real_numbers } from "./1-5-real-numbers";
import { registry as s_1_6_ratio } from "./1-6-ratio";
import { registry as s_2_1_algebraic_expressions } from "./2-1-algebraic-expressions";
import { registry as s_2_3_linear_equations } from "./2-3-linear-equations";
import { registry as s_2_4_quadratic_equations } from "./2-4-quadratic-equations";
import { registry as s_2_5_linear_inequalities } from "./2-5-linear-inequalities";
import { registry as s_2_6_functions } from "./2-6-functions";
import { registry as s_2_7_applications } from "./2-7-applications";
import { registry as s_2_8_coordinate_geometry } from "./2-8-coordinate-geometry";
import { registry as s_2_9_graphs_of_functions } from "./2-9-graphs-of-functions";
import { registry as s_3_1_lines_and_angles } from "./3-1-lines-and-angles";
import { registry as s_3_2_polygons } from "./3-2-polygons";
import { registry as s_3_5_circles } from "./3-5-circles";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const diagrams: Record<string, ComponentType<any>> = {
  ...s_1_1_integers,
  ...s_1_2_fractions,
  ...s_1_3_exponents_and_roots,
  ...s_1_4_decimals,
  ...s_1_5_real_numbers,
  ...s_1_6_ratio,
  ...s_2_1_algebraic_expressions,
  ...s_2_3_linear_equations,
  ...s_2_4_quadratic_equations,
  ...s_2_5_linear_inequalities,
  ...s_2_6_functions,
  ...s_2_7_applications,
  ...s_2_8_coordinate_geometry,
  ...s_2_9_graphs_of_functions,
  ...s_3_1_lines_and_angles,
  ...s_3_2_polygons,
  ...s_3_5_circles,
};
