// Generated by scripts/register.ts — do not edit by hand.
import type { ComponentType } from "react";
import { registry as s_1_1_integers } from "./1-1-integers";
import { registry as s_1_2_fractions } from "./1-2-fractions";
import { registry as s_1_3_exponents_and_roots } from "./1-3-exponents-and-roots";
import { registry as s_1_5_real_numbers } from "./1-5-real-numbers";
import { registry as s_3_5_circles } from "./3-5-circles";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const diagrams: Record<string, ComponentType<any>> = {
  ...s_1_1_integers,
  ...s_1_2_fractions,
  ...s_1_3_exponents_and_roots,
  ...s_1_5_real_numbers,
  ...s_3_5_circles,
};
