// Generated by scripts/register.ts — do not edit by hand.
import type { ComponentType } from "react";
import { registry as s_3_5_circles } from "./3-5-circles";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const diagrams: Record<string, ComponentType<any>> = {
  ...s_3_5_circles,
};
