// Generated by scripts/register.ts — do not edit by hand.
import type { ComponentType } from "react";
import { registry as s_1_1_integers } from "./1-1-integers";
import { registry as s_1_3_exponents_and_roots } from "./1-3-exponents-and-roots";
import { registry as s_1_5_real_numbers } from "./1-5-real-numbers";
import { registry as s_1_6_ratio } from "./1-6-ratio";
import { registry as s_1_7_percent } from "./1-7-percent";
import { registry as s_2_2_rules_of_exponents } from "./2-2-rules-of-exponents";
import { registry as s_3_5_circles } from "./3-5-circles";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const interactives: Record<string, ComponentType<any>> = {
  ...s_1_1_integers,
  ...s_1_3_exponents_and_roots,
  ...s_1_5_real_numbers,
  ...s_1_6_ratio,
  ...s_1_7_percent,
  ...s_2_2_rules_of_exponents,
  ...s_3_5_circles,
};
