// Regenerates content/{sections,diagrams,interactives}/index.ts from the files present.
// Usage: npx tsx scripts/register.ts
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { OUTLINE } from "../content/outline";

// Only sections listed in content/ready.txt (finished by their writer) are registered.
const ready = new Set(readFileSync("content/ready.txt", "utf8").split(/\s+/).filter(Boolean));
const ids = OUTLINE.map((o) => o.id).filter((id) => ready.has(id));
const has = (dir: string, id: string, ext: string) => existsSync(`content/${dir}/${id}.${ext}`);
const v = (id: string) => "s_" + id.replace(/-/g, "_");

const sectionIds = ids.filter((id) => has("sections", id, "ts"));
writeFileSync(
  "content/sections/index.ts",
  `// Generated by scripts/register.ts — do not edit by hand.
import type { Section } from "../types";
${sectionIds.map((id) => `import ${v(id)} from "./${id}";`).join("\n")}

export const SECTIONS: Record<string, Section> = {
${sectionIds.map((id) => `  "${id}": ${v(id)},`).join("\n")}
};
`,
);

function registry(dir: string, name: string, extraIds: string[]) {
  const files = readdirSync(`content/${dir}`).filter((f) => f.endsWith(".tsx")).map((f) => f.replace(/\.tsx$/, ""));
  const order = [...ids, ...extraIds];
  const present = order.filter((id) => files.includes(id));
    writeFileSync(
    `content/${dir}/index.ts`,
    `// Generated by scripts/register.ts — do not edit by hand.
import type { ComponentType } from "react";
${present.map((id) => `import { registry as ${v(id)} } from "./${id}";`).join("\n")}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const ${name}: Record<string, ComponentType<any>> = {
${present.map((id) => `  ...${v(id)},`).join("\n")}
};
`,
  );
  return present;
}

const d = registry("diagrams", "diagrams", ["conventions"]);
const i = registry("interactives", "interactives", ["conventions"]);
console.log(`sections: ${sectionIds.length}, diagram files: ${d.length}, interactive files: ${i.length}`);
