import type { Section } from "../types";

const NTS = String.raw`Note: Figure not drawn to scale.`;

const section: Section = {
  id: "3-3-triangles",
  number: "3.3",
  title: "Triangles",
  part: "geometry",
  mrPages: "96–102",
  summary: String.raw`The angle sum, the side-length rule, the Pythagorean theorem and the two special right triangles, area with any side as the base, and how the GRE uses congruent and similar triangles, which is where most hard triangle questions hide.`,

  lesson: [
    /* ---------------------------------------------------------------- */
    { kind: "heading", text: "Angles: the 180° rule" },
    {
      kind: "p",
      text: String.raw`Every [[triangle]] has three sides and three [[interior-angle|interior angles]], and the three interior angles always add up to $180^\circ$ (MR p. 96). This is the workhorse of triangle questions: whenever two angles are known, the third is free. In the figure, $x + y + z = 180$, so if $x = 52$ and $y = 67$ then $z = 61$.`,
    },
    { kind: "math", tex: String.raw`x + y + z = 180`, key: true },
    {
      kind: "diagram",
      diagram: { key: "3-3-triangles/angles", props: { variant: "interior" }, caption: String.raw`The interior angles of triangle $ABC$: $x^\circ + y^\circ + z^\circ = 180^\circ$.` },
    },
    {
      kind: "p",
      text: String.raw`A triangle can have at most one angle of $90^\circ$ or more, because two such angles would already use up $180^\circ$. Prep books call a triangle with all angles less than $90^\circ$ an [[acute-triangle|acute triangle]] and one with an angle greater than $90^\circ$ an [[obtuse-triangle|obtuse triangle]]; the ETS Math Review uses neither name, but it does use the idea, as we will see with heights.`,
    },
    {
      kind: "diagram",
      diagram: { key: "3-3-triangles/types", props: { kind: "acute-obtuse" }, caption: String.raw`Left: all three angles are less than $90^\circ$. Right: one angle is greater than $90^\circ$. In the acute one, $50 + 60 + 70 = 180$.` },
    },
    {
      kind: "p",
      text: String.raw`If you extend side $AC$ past $C$, the angle between side $BC$ and the extension is an [[exterior-angle|exterior angle]]. Because it and $z$ together form a straight angle, $w = 180 - z$, and since $x + y = 180 - z$ too, the exterior angle equals the sum of the two interior angles at the _other_ vertices: $w = x + y$ (a standard fact, though not stated in the ETS Math Review; it follows from the two facts above and the $180^\circ$ straight angle). It saves a step whenever a figure shows an extended side.`,
    },
    {
      kind: "diagram",
      diagram: { key: "3-3-triangles/angles", props: { variant: "exterior" }, caption: String.raw`The exterior angle $w^\circ$ at $C$ satisfies $w = x + y$.` },
    },

    /* ---------------------------------------------------------------- */
    { kind: "heading", text: "Sides: what lengths can a triangle have?" },
    {
      kind: "p",
      text: String.raw`Three positive numbers are the side lengths of a triangle only if each is less than the sum of the other two (MR p. 96). Another way to say it: the longest side must be shorter than the sum of the two shorter ones, because that is the only inequality that can fail. ETS states this fact without naming it; prep books call it the [[triangle-inequality|triangle inequality]]. Sides $5$, $6$ and $9$ work, since $9 < 5 + 6$. Sides $4$, $5$ and $12$ do not: $12 > 4 + 5$, so the two short sides cannot even reach across the long one, as the second figure shows.`,
    },
    {
      kind: "diagram",
      diagram: { key: "3-3-triangles/inequality", props: { variant: "ok" }, caption: String.raw`Sides $5$, $6$, $9$: the two shorter sides swing together and meet, so a triangle exists.` },
    },
    {
      kind: "diagram",
      diagram: { key: "3-3-triangles/inequality", props: { variant: "fail" }, caption: String.raw`Sides $4$, $5$, $12$: the dashed arcs show where the ends of the short sides can reach. They never meet.` },
    },
    {
      kind: "p",
      text: String.raw`The useful form for the GRE is a _range_. If two sides are $a$ and $b$, the third side $c$ satisfies $|a - b| < c < a + b$: the upper bound is the inequality above, and the lower bound comes from applying it to the other two inequalities. With sides $7$ and $10$, the third side is strictly between $3$ and $17$. Use the explorer to feel where the boundary is.`,
    },
    { kind: "math", tex: String.raw`|a - b| < c < a + b`, key: true },
    {
      kind: "interactive",
      key: "3-3-triangles/inequality-explorer",
      title: "Triangle inequality explorer",
      caption: String.raw`Drag the three sliders. A valid triangle is drawn to scale; if one side is too long, you see which inequality fails.`,
    },
    {
      kind: "aside",
      tone: "watch",
      title: "Strict inequality",
      text: String.raw`The inequality is strict. Lengths $3$, $4$, $7$ do not form a triangle: $7 = 3 + 4$ gives a flat, degenerate "triangle" with zero area. When a QC question says the triangle exists and gives two sides, expect the third to be bounded on both sides but never equal to either bound.`,
    },
    {
      kind: "p",
      text: String.raw`One more standard fact, which is not in the ETS Math Review but is handy for comparisons: in any triangle the longest side is opposite the largest angle, and the shortest side is opposite the smallest. The Math Review gives only the special case in the next section (equal sides, equal opposite angles).`,
    },

    /* ---------------------------------------------------------------- */
    { kind: "heading", text: "Equilateral, isosceles and right triangles" },
    {
      kind: "p",
      text: String.raw`A triangle with three congruent sides is an [[equilateral-triangle|equilateral triangle]]; a triangle with at least two congruent sides is an [[isosceles-triangle|isosceles triangle]] (MR p. 97). "At least" matters: every equilateral triangle is also isosceles. A triangle with no two sides equal is called [[scalene-triangle|scalene]], a name ETS does not use.`,
    },
    {
      kind: "p",
      text: String.raw`Equal sides come with equal angles: if two sides are congruent, the angles opposite them are congruent, and the converse is also true (MR p. 97). That is how you decode isosceles questions in both directions. In the isosceles figure the sides $AB$ and $BC$ are both $9$, so the angles at $A$ and $C$ (opposite $BC$ and $AB$) are equal. If each of them is $x^\circ$, the apex angle $B$ is $180 - 2x$. In an equilateral triangle all three angles are equal, so each is $60^\circ$.`,
    },
    {
      kind: "diagram",
      diagram: { key: "3-3-triangles/types", props: { kind: "isosceles" }, caption: String.raw`Isosceles: $AB = BC = 9$, so the angles at $A$ and $C$ are equal.` },
    },
    {
      kind: "diagram",
      diagram: { key: "3-3-triangles/types", props: { kind: "equilateral" }, caption: String.raw`Equilateral: all sides $7$, all angles $60^\circ$, perimeter $21$.` },
    },
    {
      kind: "aside",
      tone: "gre",
      title: "How the GRE writes it",
      text: String.raw`ETS never draws tick marks to show equal sides. Equal sides are stated in words ("$AB = BC$", "triangle $ABC$ is isosceles") or given as equal numbers on the figure. When a figure shows two equal angle measures, you may need the converse above to conclude that two sides are equal.`,
    },
    {
      kind: "p",
      text: String.raw`A triangle with an interior right angle is a [[right-triangle|right triangle]]. The side opposite the right angle is its [[hypotenuse]], and the other two sides are its [[legs]] (MR p. 97). The hypotenuse is always the longest side, and the two other angles are acute and add up to $90^\circ$. The right angle is marked with a small square.`,
    },
    {
      kind: "diagram",
      diagram: { key: "3-3-triangles/right", props: { highlight: "hypotenuse" }, caption: String.raw`The right angle is at $P$; $QR$ is the hypotenuse (highlighted). The legs are $PQ$ and $PR$.` },
    },

    /* ---------------------------------------------------------------- */
    { kind: "heading", text: "The Pythagorean theorem" },
    {
      kind: "p",
      text: String.raw`In a right triangle, the square of the hypotenuse equals the sum of the squares of the legs: the [[pythagorean-theorem|Pythagorean theorem]] (MR p. 98). With legs $a$, $b$ and hypotenuse $c$:`,
    },
    { kind: "math", tex: String.raw`a^2 + b^2 = c^2`, key: true },
    {
      kind: "diagram",
      diagram: { key: "3-3-triangles/right", props: { highlight: "all", labels: "abc" }, caption: String.raw`Legs $a$ and $b$, hypotenuse $c$.` },
    },
    {
      kind: "p",
      text: String.raw`Quick use: legs $7$ and $24$ give $c^2 = 49 + 576 = 625$, so $c = 25$. If instead the hypotenuse is $11$ and one leg is $4$, the other leg satisfies $x^2 = 121 - 16 = 105$, so $x = \sqrt{105} \approx 10.2$; take the positive root, since a length is positive. The usual error is to put the hypotenuse on the wrong side of the equation, so always identify it first (opposite the right angle) and put it alone on one side.`,
    },
    {
      kind: "aside",
      tone: "tip",
      title: "Pythagorean triples: memorize these",
      text: String.raw`Some right triangles have all three sides integers, and the GRE loves them because the arithmetic disappears. The common ones are $3$-$4$-$5$, $5$-$12$-$13$, $8$-$15$-$17$ and $7$-$24$-$25$, and every multiple of a triple is again a triple (such as $6$-$8$-$10$ and $9$-$12$-$15$). This is a test-taking shortcut, not something the ETS Math Review lists. See a leg of $15$ and a hypotenuse of $17$ in a figure? The other leg is $8$ with no computation.`,
    },
    {
      kind: "p",
      text: String.raw`Two situations turn up all the time. A rectangle's diagonal is the hypotenuse of a right triangle whose legs are the rectangle's sides. And two perpendicular segments from a point, such as "walks $9$ miles north and then $12$ miles east", leave you the straight-line distance $15$.`,
    },

    /* ---------------------------------------------------------------- */
    { kind: "heading", text: "Two special right triangles" },
    {
      kind: "p",
      text: String.raw`Two right triangles come up so often that their side ratios are worth knowing cold (MR pp. 99–100). The first is the [[isosceles-right-triangle|isosceles right triangle]], with angles $45^\circ$, $45^\circ$, $90^\circ$. The legs are equal, say $x$, so the hypotenuse $y$ satisfies $y^2 = x^2 + x^2 = 2x^2$, giving $y = x\sqrt{2}$. The sides are in the ratio $1 : 1 : \sqrt{2}$. Example: a hypotenuse of $10$ means each leg is $\frac{10}{\sqrt{2}} = 5\sqrt{2}$.`,
    },
    {
      kind: "diagram",
      diagram: { key: "3-3-triangles/iso-right", caption: String.raw`$45^\circ$-$45^\circ$-$90^\circ$: sides $x$, $x$, $x\sqrt{2}$.` },
    },
    {
      kind: "p",
      text: String.raw`The second is the [[thirty-sixty-ninety-triangle|30°-60°-90° triangle]], which is half of an equilateral triangle cut down the middle by a height. The short side, opposite the $30^\circ$ angle, is half of the hypotenuse, because the cut halves an equilateral side. If the short side is $x$, the hypotenuse is $2x$ and the remaining side is $y$ with $x^2 + y^2 = 4x^2$, so $y = x\sqrt{3}$. The ratio is $1 : \sqrt{3} : 2$. Example: with short side $7$, the sides are $7$, $7\sqrt{3}$ and $14$.`,
    },
    {
      kind: "diagram",
      diagram: { key: "3-3-triangles/thirty-sixty", caption: String.raw`$30^\circ$-$60^\circ$-$90^\circ$: sides $x$, $x\sqrt{3}$, $2x$. The dashed half is the mirror image that completes the equilateral triangle.` },
    },
    {
      kind: "math",
      tex: String.raw`45^\circ\text{-}45^\circ\text{-}90^\circ:\; 1 : 1 : \sqrt{2} \qquad 30^\circ\text{-}60^\circ\text{-}90^\circ:\; 1 : \sqrt{3} : 2`,
      key: true,
    },
    {
      kind: "interactive",
      key: "3-3-triangles/special-explorer",
      title: "Special right triangle explorer",
      caption: String.raw`Pick a triangle type, choose which side you know, and set its length. The explorer gives the other sides in exact form.`,
    },
    {
      kind: "aside",
      tone: "gre",
      title: "How the GRE hides them",
      text: String.raw`Look for $45^\circ$, $30^\circ$ or $60^\circ$ angles, for a square's diagonal (an isosceles right triangle with the diagonal as hypotenuse), and for an equilateral triangle's height (the $30^\circ$-$60^\circ$-$90^\circ$ half). An equilateral triangle with side $s$ has height $\frac{s\sqrt{3}}{2}$, a one-line application of the ratio, and therefore area $\frac{s^2\sqrt{3}}{4}$.`,
    },
    {
      kind: "aside",
      tone: "watch",
      text: String.raw`The most common slip is mixing up which leg is which. The side opposite $30^\circ$ is the _shortest_, $x$; the side opposite $60^\circ$ is $x\sqrt{3}$ (about $1.73x$); the hypotenuse $2x$ is opposite $90^\circ$. In the $45^\circ$ triangle, going from a leg to the hypotenuse multiplies by $\sqrt{2}$, and going from the hypotenuse to a leg divides by $\sqrt{2}$.`,
    },

    /* ---------------------------------------------------------------- */
    { kind: "heading", text: "Area: any side can be the base" },
    {
      kind: "p",
      text: String.raw`Any side of a triangle can be chosen as its [[base]]. The [[height]] that corresponds to that base is the perpendicular segment from the opposite vertex to the base, or to an extension of the base (MR p. 100). Depending on context, "base" and "height" also name the _lengths_. The [[triangle-area|area]] is half of base times height:`,
    },
    { kind: "math", tex: String.raw`A = \frac{bh}{2}`, key: true },
    {
      kind: "diagram",
      diagram: { key: "3-3-triangles/base-height", props: { variant: "inside", b: "b", h: "h" }, caption: String.raw`Base $b$ and the corresponding height $h$, which meets the base at a right angle.` },
    },
    {
      kind: "p",
      text: String.raw`The height can be a segment inside the triangle, a leg (in a right triangle, one leg is the height for the other), or a segment _outside_ the triangle that lands on the extended base. In all three triangles below the base is $12$ and the height is $5$, so all three areas are $\frac{12 \cdot 5}{2} = 30$. The shape of the triangle is irrelevant: only base and corresponding height matter.`,
    },
    {
      kind: "diagram",
      diagram: { key: "3-3-triangles/base-height", props: { variant: "all" }, caption: String.raw`Height inside, a leg, and outside the triangle: each has base $12$, height $5$, area $30$.` },
    },
    {
      kind: "p",
      text: String.raw`Because any side may be the base, the same triangle has three base-and-height pairs, all giving the same area. This is a powerful trick: if you know the area and one pair, you can find the height to a different side. In the figure, triangle $KLM$ is obtuse at $K$. With base $KL$ the height $h$ falls outside the triangle; with base $ML$ the height is $k$. Whatever the numbers, $\frac{KL \cdot h}{2} = \frac{ML \cdot k}{2}$.`,
    },
    {
      kind: "diagram",
      diagram: { key: "3-3-triangles/any-base", caption: String.raw`The same triangle $KLM$ with two choices of base: $KL$ with height $h$ (outside), and $ML$ with height $k$ (outside).` },
    },
    {
      kind: "aside",
      tone: "watch",
      title: "Height is not a side",
      text: String.raw`In a non-right triangle, a side is not a height. The classic trap is to multiply two sides and halve. That works only if the two sides are the legs of a right triangle. In an obtuse triangle, find the height using a $30^\circ$-$60^\circ$-$90^\circ$ or $45^\circ$-$45^\circ$-$90^\circ$ triangle built on the extension of the base, or from a stated area.`,
    },

    /* ---------------------------------------------------------------- */
    { kind: "heading", text: "Congruent triangles" },
    {
      kind: "p",
      text: String.raw`Two triangles with the same shape and size are [[congruent-triangles|congruent triangles]]. Precisely, they are congruent if their vertices can be matched up so that the [[corresponding-parts|corresponding]] angles and corresponding sides are congruent (MR p. 101). The _order of the letters_ carries the matching: "triangles $PQR$ and $STU$ are congruent" means $P \leftrightarrow S$, $Q \leftrightarrow T$, $R \leftrightarrow U$, so $PQ$ matches $ST$, $QR$ matches $TU$, and $PR$ matches $SU$. Always read the matching from the letters, not from how the figure looks.`,
    },
    {
      kind: "diagram",
      diagram: { key: "3-3-triangles/congruent", props: { highlight: "corr" }, caption: String.raw`Triangles $PQR$ and $STU$ are congruent: $a$ matches $a$, $b$ matches $b$, $c$ matches $c$. $T$ is the apex of $STU$, which sits "backwards" compared with $Q$.` },
    },
    {
      kind: "p",
      text: String.raw`You do not need all six pairs to be sure. Each of these four conditions is enough (MR p. 101): [[sss|SSS]] (the three sides of one triangle are congruent to the three sides of the other); [[sas|SAS]] (two sides and the [[included-angle|included angle]]); [[asa|ASA]] (two angles and the [[included-side|included side]]); and [[aas|AAS]] (two angles and a side that is _not_ between them, which follows from ASA because the third angles must also match, since the angles add up to $180^\circ$).`,
    },
    {
      kind: "diagram",
      diagram: { key: "3-3-triangles/congruent", props: { highlight: "sss" }, caption: String.raw`SSS: all three sides.` },
    },
    {
      kind: "diagram",
      diagram: { key: "3-3-triangles/congruent", props: { highlight: "sas" }, caption: String.raw`SAS: sides $a$ and $b$ with the angle $y^\circ$ between them.` },
    },
    {
      kind: "diagram",
      diagram: { key: "3-3-triangles/congruent", props: { highlight: "asa" }, caption: String.raw`ASA: angles $x^\circ$ and $y^\circ$ with side $a$ between them.` },
    },
    {
      kind: "diagram",
      diagram: { key: "3-3-triangles/congruent", props: { highlight: "aas" }, caption: String.raw`AAS: angles $x^\circ$ and $y^\circ$ with side $b$, which is not between them.` },
    },
    {
      kind: "aside",
      tone: "watch",
      title: "What does not work",
      text: String.raw`Three equal angles (AAA) force the same shape, but not the same size, so they do not give congruence. Two sides and an angle that is _not_ between them (SSA) is not on the list either: it can describe two different triangles. The ETS Math Review lists only the four conditions above, so a GRE answer that needs more should be treated with suspicion.`,
    },

    /* ---------------------------------------------------------------- */
    { kind: "heading", text: "Similar triangles" },
    {
      kind: "p",
      text: String.raw`Two triangles with the same shape but not necessarily the same size are [[similar-triangles|similar triangles]]. Precisely, the vertices can be matched up so that corresponding angles are congruent or, equivalently, the lengths of corresponding sides have the same ratio, called the [[scale-factor|scale factor]] of the similarity (MR p. 102). In the figure, triangles $ABC$ and $DEF$ are similar with $A \leftrightarrow D$, $B \leftrightarrow E$, $C \leftrightarrow F$:`,
    },
    {
      kind: "math",
      tex: String.raw`\frac{DE}{AB} = \frac{EF}{BC} = \frac{DF}{AC} = \frac{4}{6} = \frac{6}{9} = \frac{8}{12} = \frac{2}{3}`,
    },
    {
      kind: "diagram",
      diagram: { key: "3-3-triangles/similar", caption: String.raw`The scale factor from $ABC$ to $DEF$ is $\frac{2}{3}$ (and from $DEF$ to $ABC$ it is $\frac{3}{2}$).` },
    },
    {
      kind: "p",
      text: String.raw`Notice that the angles do the work: you can prove similarity by showing two matching angles (the third must then match too), or by showing equal ratios of all three pairs of sides. Cross-multiplying gives other useful proportions, for example $\frac{AB}{BC} = \frac{DE}{EF}$. And any two $30^\circ$-$60^\circ$-$90^\circ$ triangles are similar, as are any two $45^\circ$-$45^\circ$-$90^\circ$ triangles. Congruent triangles are the special case with scale factor $1$.`,
    },
    {
      kind: "p",
      text: String.raw`One fact beyond the ETS Math Review, but standard and heavily used: if the scale factor is $k$, then _all_ lengths scale by $k$ (including heights and perimeters), while the _area_ scales by $k^2$. With $k = \frac{2}{3}$ above, the perimeter of $DEF$ is $\frac{2}{3}$ of the perimeter of $ABC$, and the area of $DEF$ is $\frac{4}{9}$ of the area of $ABC$.`,
    },
    {
      kind: "p",
      text: String.raw`The most common source of similar triangles on the GRE is a segment drawn parallel to one side. In the figure, $DE$ is parallel to $BC$, so the angles at $D$ and $B$ are corresponding angles of parallel lines, as are the angles at $E$ and $C$ (MR p. 94), and the angle at $A$ is shared. Triangles $ADE$ and $ABC$ are therefore similar, with $\frac{AD}{AB} = \frac{AE}{AC} = \frac{DE}{BC}$. Right triangles that share an acute angle work the same way.`,
    },
    {
      kind: "diagram",
      diagram: { key: "3-3-triangles/nested", props: { variant: "lesson" }, caption: String.raw`$DE$ parallel to $BC$ cuts off a small triangle $ADE$ that is similar to $ABC$ (the angle at $A$ is shared).` },
    },
    {
      kind: "aside",
      tone: "tip",
      title: "Whole versus part",
      text: String.raw`When $DE$ cuts $AB$ into pieces, the ratio is usually given for the pieces ($AD$ and $DB$), but similarity compares $AD$ with the whole $AB$. If $AD = 4$ and $DB = 6$, the scale factor is $\frac{4}{4+6} = \frac{2}{5}$, not $\frac{4}{6}$. The area of the trapezoid $DBCE$ is then $1 - \frac{4}{25} = \frac{21}{25}$ of the area of $ABC$.`,
    },

    /* ---------------------------------------------------------------- */
    { kind: "heading", text: "Putting it together" },
    {
      kind: "p",
      text: String.raw`A hard triangle question rarely uses one idea alone. A typical route: use the angle sum to find a missing angle, notice that it makes the triangle isosceles or a special right triangle, use the ratio to get a side, and finish with $\frac{bh}{2}$ using whichever side and height are convenient. When two triangles appear, ask whether they are similar (shared angle, parallel lines) before reaching for the Pythagorean theorem.`,
    },
    {
      kind: "aside",
      tone: "watch",
      title: "Classic traps",
      text: String.raw`Using $\frac{ab}{2}$ for a triangle that is not right-angled; forgetting that an obtuse triangle's height falls outside; applying the Pythagorean theorem with the wrong side as hypotenuse; mixing up $\sqrt{2}$ and $\sqrt{3}$ in the special triangles; letting the picture decide which vertices correspond instead of the letter order; forgetting that areas of similar triangles scale by the _square_ of the scale factor; and accepting side lengths that violate the triangle inequality. Figures are drawn to scale unless the question says otherwise, but only the stated measures are guaranteed.`,
    },
  ],

  terms: [
    {
      id: "triangle",
      term: "triangle",
      turkish: "üçgen",
      definition: String.raw`A figure with three sides and three interior angles. A triangle is named by its vertices, for example "triangle $ABC$".`,
      diagram: { key: "3-3-triangles/types", props: { kind: "scalene" } },
      source: "MR p. 96",
    },
    {
      id: "interior-angle",
      term: "interior angle",
      turkish: "iç açı",
      definition: String.raw`An angle of the triangle formed by two of its sides at a vertex. The three interior angles of a triangle add up to $180^\circ$.`,
      formula: String.raw`x + y + z = 180^\circ`,
      diagram: { key: "3-3-triangles/angles", props: { variant: "interior" } },
      source: "MR p. 96",
    },
    {
      id: "exterior-angle",
      term: "exterior angle",
      turkish: "dış açı",
      definition: String.raw`The angle between one side of a triangle and the extension of an adjacent side. It equals the sum of the two interior angles at the other vertices.`,
      formula: String.raw`w = x + y`,
      diagram: { key: "3-3-triangles/angles", props: { variant: "exterior" } },
      note: "Not named in the ETS Math Review",
    },
    {
      id: "acute-triangle",
      term: "acute triangle",
      turkish: "dar açılı üçgen",
      definition: String.raw`A triangle whose three angles are all less than $90^\circ$.`,
      diagram: { key: "3-3-triangles/types", props: { kind: "acute-obtuse" } },
      note: "Not named in the ETS Math Review",
    },
    {
      id: "obtuse-triangle",
      term: "obtuse triangle",
      turkish: "geniş açılı üçgen",
      definition: String.raw`A triangle with one angle greater than $90^\circ$. Its height onto either side next to the obtuse angle falls outside the triangle.`,
      diagram: { key: "3-3-triangles/types", props: { kind: "acute-obtuse" } },
      note: "Not named in the ETS Math Review",
    },
    {
      id: "triangle-inequality",
      term: "triangle inequality",
      turkish: "üçgen eşitsizliği",
      definition: String.raw`The length of each side of a triangle must be less than the sum of the lengths of the other two sides. Equivalently, the third side lies strictly between the difference and the sum of the other two.`,
      formula: String.raw`|a - b| < c < a + b`,
      diagram: { key: "3-3-triangles/inequality", props: { variant: "fail" } },
      source: "MR p. 96",
      note: "The fact is in the Math Review, but ETS does not name it",
    },
    {
      id: "equilateral-triangle",
      term: "equilateral triangle",
      turkish: "eşkenar üçgen",
      definition: String.raw`A triangle with three congruent sides. Its three interior angles are equal, each $60^\circ$.`,
      diagram: { key: "3-3-triangles/types", props: { kind: "equilateral" } },
      source: "MR p. 97",
    },
    {
      id: "isosceles-triangle",
      term: "isosceles triangle",
      turkish: "ikizkenar üçgen",
      definition: String.raw`A triangle with at least two congruent sides. The angles opposite the two congruent sides are congruent, and conversely.`,
      diagram: { key: "3-3-triangles/types", props: { kind: "isosceles" } },
      source: "MR p. 97",
    },
    {
      id: "scalene-triangle",
      term: "scalene triangle",
      turkish: "çeşitkenar üçgen",
      definition: String.raw`A triangle with no two sides congruent.`,
      diagram: { key: "3-3-triangles/types", props: { kind: "scalene" } },
      note: "Not named in the ETS Math Review",
    },
    {
      id: "right-triangle",
      term: "right triangle",
      turkish: "dik üçgen",
      definition: String.raw`A triangle with an interior right angle, drawn with a small square at that vertex. The other two angles are acute and add up to $90^\circ$.`,
      diagram: { key: "3-3-triangles/right", props: { highlight: "none" } },
      source: "MR p. 97",
    },
    {
      id: "hypotenuse",
      term: "hypotenuse",
      turkish: "hipotenüs",
      definition: String.raw`The side opposite the right angle of a right triangle. It is the longest side.`,
      diagram: { key: "3-3-triangles/right", props: { highlight: "hypotenuse" } },
      source: "MR p. 97",
    },
    {
      id: "legs",
      term: "legs",
      turkish: "dik kenarlar",
      definition: String.raw`The two sides of a right triangle that form the right angle (the sides other than the hypotenuse).`,
      diagram: { key: "3-3-triangles/right", props: { highlight: "legs" } },
      source: "MR p. 97",
    },
    {
      id: "pythagorean-theorem",
      term: "Pythagorean theorem",
      turkish: "Pisagor teoremi / Pisagor bağıntısı",
      definition: String.raw`In a right triangle, the square of the length of the hypotenuse equals the sum of the squares of the lengths of the legs.`,
      formula: String.raw`a^2 + b^2 = c^2`,
      diagram: { key: "3-3-triangles/right", props: { highlight: "all", labels: "abc" } },
      source: "MR p. 98",
    },
    {
      id: "pythagorean-triple",
      term: "Pythagorean triple",
      turkish: "Pisagor üçlüsü",
      definition: String.raw`Three positive integers that satisfy $a^2 + b^2 = c^2$, such as $3, 4, 5$ and $5, 12, 13$. Every multiple of a triple is another triple.`,
      formula: String.raw`3^2 + 4^2 = 5^2`,
      diagram: { key: "3-3-triangles/right", props: { highlight: "all", labels: "abc" } },
      note: "Not named in the ETS Math Review",
    },
    {
      id: "isosceles-right-triangle",
      term: "isosceles right triangle (45°-45°-90°)",
      turkish: "ikizkenar dik üçgen (45°-45°-90°)",
      definition: String.raw`A right triangle whose legs are congruent, with $45^\circ$ angles opposite the legs. Its sides are in the ratio $1 : 1 : \sqrt{2}$.`,
      formula: String.raw`x : x : x\sqrt{2}`,
      diagram: { key: "3-3-triangles/iso-right" },
      source: "MR p. 99",
    },
    {
      id: "thirty-sixty-ninety-triangle",
      term: "30°-60°-90° triangle",
      turkish: "30°-60°-90° üçgeni (dik üçgen)",
      definition: String.raw`A right triangle with angles of $30^\circ$, $60^\circ$ and $90^\circ$; it is half of an equilateral triangle. Its sides are in the ratio $1 : \sqrt{3} : 2$, the shortest side being opposite $30^\circ$.`,
      formula: String.raw`x : x\sqrt{3} : 2x`,
      diagram: { key: "3-3-triangles/thirty-sixty" },
      source: "MR pp. 99–100",
    },
    {
      id: "base",
      term: "base (of a triangle)",
      turkish: "taban",
      definition: String.raw`Any side of a triangle can be used as a base. "Base" may also mean the length of that side.`,
      diagram: { key: "3-3-triangles/base-height", props: { variant: "inside", b: "b", h: "h", highlight: "base" } },
      source: "MR p. 100",
    },
    {
      id: "height",
      term: "height (of a triangle)",
      turkish: "yükseklik",
      definition: String.raw`The height that corresponds to a base is the perpendicular segment from the opposite vertex to the base (or to an extension of the base). In an obtuse triangle it can lie outside the triangle. "Height" may also mean its length.`,
      diagram: { key: "3-3-triangles/base-height", props: { variant: "outside", b: "b", h: "h", highlight: "height" } },
      source: "MR p. 100",
    },
    {
      id: "triangle-area",
      term: "area of a triangle",
      turkish: "üçgenin alanı",
      definition: String.raw`One half of the product of a base and its corresponding height. All three base-and-height choices give the same area.`,
      formula: String.raw`A = \frac{bh}{2}`,
      diagram: { key: "3-3-triangles/base-height", props: { variant: "inside", b: "b", h: "h", highlight: "both" } },
      source: "MR p. 100",
    },
    {
      id: "congruent-triangles",
      term: "congruent triangles",
      turkish: "eş üçgenler",
      definition: String.raw`Triangles with the same shape and size: their vertices can be matched up so that corresponding angles and corresponding sides are congruent.`,
      diagram: { key: "3-3-triangles/congruent", props: { highlight: "corr" } },
      source: "MR p. 101",
    },
    {
      id: "corresponding-parts",
      term: "corresponding parts",
      turkish: "karşılıklı elemanlar / eş elemanlar",
      definition: String.raw`The angles and sides that are matched when two triangles are congruent or similar. The order of the letters in "triangles $PQR$ and $STU$" tells you the match: $P$ with $S$, $Q$ with $T$, $R$ with $U$.`,
      diagram: { key: "3-3-triangles/congruent", props: { highlight: "corr" } },
      source: "MR p. 101",
    },
    {
      id: "included-angle",
      term: "included angle",
      turkish: "iki kenar arasındaki açı",
      definition: String.raw`The angle formed by two given sides, between them. SAS needs the angle to be included.`,
      diagram: { key: "3-3-triangles/congruent", props: { highlight: "sas" } },
      source: "MR p. 101",
      note: "Used by ETS, not defined separately",
    },
    {
      id: "included-side",
      term: "included side",
      turkish: "iki açı arasındaki kenar",
      definition: String.raw`The side that lies between two given angles (it joins their vertices). ASA needs the side to be included.`,
      diagram: { key: "3-3-triangles/congruent", props: { highlight: "asa" } },
      source: "MR p. 101",
      note: "Used by ETS, not defined separately",
    },
    {
      id: "sss",
      term: "SSS (Side-Side-Side)",
      turkish: "kenar-kenar-kenar (KKK) eşlik",
      definition: String.raw`If the three sides of one triangle are congruent to the three sides of another, the triangles are congruent.`,
      diagram: { key: "3-3-triangles/congruent", props: { highlight: "sss" } },
      source: "MR p. 101",
    },
    {
      id: "sas",
      term: "SAS (Side-Angle-Side)",
      turkish: "kenar-açı-kenar (KAK) eşlik",
      definition: String.raw`If two sides and the included angle of one triangle are congruent to two sides and the included angle of another, the triangles are congruent.`,
      diagram: { key: "3-3-triangles/congruent", props: { highlight: "sas" } },
      source: "MR p. 101",
    },
    {
      id: "asa",
      term: "ASA (Angle-Side-Angle)",
      turkish: "açı-kenar-açı (AKA) eşlik",
      definition: String.raw`If two angles and the included side of one triangle are congruent to two angles and the included side of another, the triangles are congruent.`,
      diagram: { key: "3-3-triangles/congruent", props: { highlight: "asa" } },
      source: "MR p. 101",
    },
    {
      id: "aas",
      term: "AAS (Angle-Angle-Side)",
      turkish: "açı-açı-kenar (AAK) eşlik",
      definition: String.raw`If two angles and a side that is not between them in one triangle are congruent to the matching parts of another, the triangles are congruent. It follows from ASA, because the third angles must also be congruent.`,
      diagram: { key: "3-3-triangles/congruent", props: { highlight: "aas" } },
      source: "MR p. 101",
    },
    {
      id: "similar-triangles",
      term: "similar triangles",
      turkish: "benzer üçgenler",
      definition: String.raw`Triangles with the same shape but not necessarily the same size: their vertices can be matched up so that corresponding angles are congruent or, equivalently, the lengths of corresponding sides have the same ratio.`,
      diagram: { key: "3-3-triangles/similar" },
      source: "MR p. 102",
    },
    {
      id: "scale-factor",
      term: "scale factor (of similarity)",
      turkish: "benzerlik oranı",
      definition: String.raw`The common ratio of the lengths of corresponding sides of two similar triangles. Areas then have ratio equal to the square of the scale factor (a standard fact, not stated in the Math Review).`,
      formula: String.raw`\frac{DE}{AB} = \frac{EF}{BC} = \frac{DF}{AC}`,
      diagram: { key: "3-3-triangles/similar" },
      source: "MR p. 102",
    },
  ],

  examples: [
    {
      id: "ex-obtuse-area",
      type: "qc",
      difficulty: "medium",
      diagram: { key: "3-3-triangles/obtuse-question", caption: NTS },
      given: String.raw`In triangle $PQR$, $QP = 8$, $QR = 5$, and the measure of angle $PQR$ is $120^\circ$.`,
      quantityA: String.raw`The area of triangle $PQR$`,
      quantityB: String.raw`$18$`,
      answer: "B",
      explanation: [
        String.raw`The trap is $\frac{1}{2}(8)(5) = 20 > 18$. That would be right only if $QP$ and $QR$ were perpendicular, and here the angle between them is $120^\circ$.`,
        String.raw`Take $QP = 8$ as the base. The height from $R$ falls outside the triangle, on the extension of $PQ$ past $Q$. The angle between $QR$ and that extension is $180^\circ - 120^\circ = 60^\circ$, so $QR = 5$ is the hypotenuse of a $30^\circ$-$60^\circ$-$90^\circ$ triangle whose side opposite the $60^\circ$ angle is the height: $h = \frac{5\sqrt{3}}{2}$.`,
        String.raw`Area $= \frac{1}{2}(8)\left(\frac{5\sqrt{3}}{2}\right) = 10\sqrt{3} \approx 17.3$, which is less than $18$. Quantity B is greater.`,
      ],
    },
    {
      id: "ex-two-special",
      type: "mc1",
      difficulty: "hard",
      diagram: { key: "3-3-triangles/two-special", caption: NTS },
      stem: String.raw`In triangle $ABC$, $D$ is a point on $BC$ such that $AD$ is perpendicular to $BC$ and $AD = 6$. The measure of angle $B$ is $30^\circ$ and the measure of angle $C$ is $45^\circ$. What is the perimeter of triangle $ABC$?`,
      choices: [
        String.raw`$18 + 6\sqrt{2}$`,
        String.raw`$18 + 6\sqrt{3}$`,
        String.raw`$12 + 6\sqrt{2} + 6\sqrt{3}$`,
        String.raw`$18 + 6\sqrt{2} + 6\sqrt{3}$`,
        String.raw`$18 + 12\sqrt{3}$`,
      ],
      answer: 3,
      explanation: [
        String.raw`The height $AD$ cuts triangle $ABC$ into two right triangles. Handle each with its special ratio.`,
        String.raw`Triangle $ABD$ is a $30^\circ$-$60^\circ$-$90^\circ$ triangle. $AD = 6$ is opposite the $30^\circ$ angle, so it is the short side $x$: $AB = 2x = 12$ and $BD = x\sqrt{3} = 6\sqrt{3}$.`,
        String.raw`Triangle $ADC$ is a $45^\circ$-$45^\circ$-$90^\circ$ triangle with both legs $6$: $DC = 6$ and $AC = 6\sqrt{2}$.`,
        String.raw`Perimeter $= AB + BC + AC = 12 + (6\sqrt{3} + 6) + 6\sqrt{2} = 18 + 6\sqrt{2} + 6\sqrt{3} \approx 36.9$. The tempting answer $12 + 6\sqrt{2} + 6\sqrt{3}$ leaves out $DC$.`,
      ],
    },
    {
      id: "ex-right-nested",
      type: "ne",
      difficulty: "hard",
      diagram: { key: "3-3-triangles/right-nested", caption: NTS },
      stem: String.raw`In the figure, triangle $ABC$ has a right angle at $C$, with $AC = 12$ and $BC = 9$. Point $D$ is on $AC$, point $E$ is on $AB$, $DE$ is perpendicular to $AC$, and $DE = 6$. What is the area of quadrilateral $DCBE$?`,
      answer: { kind: "decimal", value: "30" },
      explanation: [
        String.raw`Triangles $ADE$ and $ACB$ are both right triangles and share the angle at $A$, so they are similar, with $\frac{DE}{CB} = \frac{6}{9} = \frac{2}{3}$.`,
        String.raw`Then $AD = \frac{2}{3}(12) = 8$. (Check: $AB = 15$ and $AE = 10$ by the $3$-$4$-$5$ pattern, and $6$-$8$-$10$ is the smaller triangle.)`,
        String.raw`Area of $ABC = \frac{1}{2}(12)(9) = 54$. Area of $ADE = \frac{1}{2}(8)(6) = 24$. The quadrilateral is what is left: $54 - 24 = 30$.`,
        String.raw`Check with the scale factor: $54 \cdot \frac{4}{9} = 24$. Same.`,
      ],
    },
    {
      id: "ex-third-side",
      type: "mcm",
      difficulty: "medium",
      stem: String.raw`The lengths of two sides of a triangle are $6$ and $11$. The length of the third side is an integer. Indicate all of the following that could be the length of the third side.`,
      choices: [String.raw`$4$`, String.raw`$5$`, String.raw`$6$`, String.raw`$11$`, String.raw`$16$`, String.raw`$17$`],
      answer: [2, 3, 4],
      explanation: [
        String.raw`The third side $c$ must satisfy $|11 - 6| < c < 11 + 6$, so $5 < c < 17$.`,
        String.raw`$5$ and $17$ are the boundary values and are excluded (a degenerate triangle with zero area). $4$ is too short. The values $6$, $11$ and $16$ all lie strictly between $5$ and $17$.`,
        String.raw`Check $6$: $6 + 6 = 12 > 11$, fine, so the triangle with sides $6, 6, 11$ exists (isosceles). Check $16$: $11 + 6 = 17 > 16$, fine.`,
      ],
    },
  ],

  quick: [
    {
      id: "q-angle-sum",
      prompt: String.raw`Two angles of a triangle measure $38^\circ$ and $71^\circ$. What is the third?`,
      answer: String.raw`$71^\circ$`,
      explanation: String.raw`$180 - 38 - 71 = 71$. (So the triangle is isosceles: two angles are equal.)`,
    },
    {
      id: "q-inequality",
      prompt: String.raw`Can $6$, $6$ and $13$ be the side lengths of a triangle?`,
      answer: String.raw`No`,
      explanation: String.raw`$13 > 6 + 6 = 12$: the longest side is too long.`,
    },
    {
      id: "q-pythag",
      prompt: String.raw`A right triangle has legs $9$ and $40$. How long is its hypotenuse?`,
      answer: String.raw`$41$`,
      explanation: String.raw`$81 + 1600 = 1681 = 41^2$ (a $9$-$40$-$41$ triple).`,
    },
    {
      id: "q-45",
      prompt: String.raw`An isosceles right triangle has hypotenuse $14$. How long is each leg?`,
      answer: String.raw`$7\sqrt{2}$`,
      explanation: String.raw`Hypotenuse $= x\sqrt{2}$, so $x = \frac{14}{\sqrt{2}} = 7\sqrt{2} \approx 9.9$.`,
    },
    {
      id: "q-3060",
      prompt: String.raw`In a $30^\circ$-$60^\circ$-$90^\circ$ triangle the side opposite $60^\circ$ is $5\sqrt{3}$. What are the other two sides?`,
      answer: String.raw`$5$ and $10$`,
      explanation: String.raw`The side opposite $60^\circ$ is $x\sqrt{3}$, so $x = 5$ (opposite $30^\circ$) and the hypotenuse is $2x = 10$.`,
    },
    {
      id: "q-area-scale",
      prompt: String.raw`Triangle $ABC$ is similar to triangle $DEF$, and $AB$ is $\frac{3}{5}$ as long as the corresponding side $DE$. If the area of $DEF$ is $50$, what is the area of $ABC$?`,
      answer: String.raw`$18$`,
      explanation: String.raw`Areas scale by the square of the scale factor: $50 \cdot \frac{9}{25} = 18$.`,
    },
  ],

  quiz: {
    questions: [
      {
        id: "z-iso-cases",
        type: "qc",
        difficulty: "hard",
        given: String.raw`A triangle has perimeter $30$. It is isosceles, and one of its sides has length $12$.`,
        quantityA: String.raw`The length of the shortest side of the triangle`,
        quantityB: String.raw`$7$`,
        answer: "D",
        explanation: [
          String.raw`A side of length $12$ can be one of the two equal sides, or the odd side.`,
          String.raw`Case 1: the equal sides are $12$ and $12$. The third side is $30 - 24 = 6$. Triangle inequality: $12 < 12 + 6$ and $6 < 24$, so this triangle exists, and the shortest side is $6 < 7$.`,
          String.raw`Case 2: the odd side is $12$, the equal sides are $\frac{30 - 12}{2} = 9$ each. Check: $12 < 9 + 9$, so this exists too, and the shortest side is $9 > 7$.`,
          String.raw`Both cases are possible, and they lead to different comparisons, so the answer is D (the relationship cannot be determined).`,
        ],
      },
      {
        id: "z-special-areas",
        type: "qc",
        difficulty: "medium",
        given: String.raw`Triangle $T_1$ is a right triangle with two congruent sides and hypotenuse $12$. Triangle $T_2$ is an equilateral triangle with side $8$.`,
        quantityA: String.raw`The area of $T_1$`,
        quantityB: String.raw`The area of $T_2$`,
        answer: "A",
        explanation: [
          String.raw`$T_1$ is a $45^\circ$-$45^\circ$-$90^\circ$ triangle. Each leg is $\frac{12}{\sqrt{2}}$, so the area is $\frac{1}{2}\cdot\frac{144}{2} = 36$.`,
          String.raw`$T_2$: the height cuts it into two $30^\circ$-$60^\circ$-$90^\circ$ triangles with hypotenuse $8$ and short side $4$, so the height is $4\sqrt{3}$. Area $= \frac{1}{2}(8)(4\sqrt{3}) = 16\sqrt{3} \approx 27.7$.`,
          String.raw`$36 > 27.7$, so Quantity A is greater.`,
        ],
      },
      {
        id: "z-iso-inequality",
        type: "qc",
        difficulty: "hard",
        given: String.raw`A triangle is isosceles with two sides of lengths $8$ and $17$. (The third side is not given.)`,
        quantityA: String.raw`The perimeter of the triangle`,
        quantityB: String.raw`$40$`,
        answer: "A",
        explanation: [
          String.raw`The third side equals one of the given sides: it is $8$ or $17$.`,
          String.raw`If it is $8$, the sides are $8, 8, 17$, but $8 + 8 = 16 < 17$ violates the triangle inequality, so this triangle does not exist.`,
          String.raw`So the third side is $17$: the sides are $8, 17, 17$ (valid: $17 < 8 + 17$), and the perimeter is $42 > 40$.`,
          String.raw`Quantity A is greater. The shortcut perimeter $33$ would have given the wrong comparison.`,
        ],
      },
      {
        id: "z-3060-area",
        type: "mc1",
        difficulty: "medium",
        stem: String.raw`A $30^\circ$-$60^\circ$-$90^\circ$ triangle has area $18\sqrt{3}$. What is the length of its hypotenuse?`,
        choices: [String.raw`$6$`, String.raw`$6\sqrt{3}$`, String.raw`$12$`, String.raw`$18$`, String.raw`$12\sqrt{3}$`],
        answer: 2,
        explanation: [
          String.raw`Let the short side (opposite $30^\circ$) be $x$. The legs are $x$ and $x\sqrt{3}$, so the area is $\frac{1}{2}(x)(x\sqrt{3}) = \frac{x^2\sqrt{3}}{2}$.`,
          String.raw`Set $\frac{x^2\sqrt{3}}{2} = 18\sqrt{3}$, so $x^2 = 36$ and $x = 6$ (positive).`,
          String.raw`The hypotenuse is $2x = 12$. The choice $6\sqrt{3}$ is the longer leg, and $6$ is the shorter leg.`,
        ],
      },
      {
        id: "z-similar-perimeters",
        type: "mc1",
        difficulty: "medium",
        stem: String.raw`Triangle $ABC$ is similar to triangle $DEF$. The perimeter of $ABC$ is $24$, the perimeter of $DEF$ is $16$, and the area of $ABC$ is $72$. What is the area of $DEF$?`,
        choices: [String.raw`$16$`, String.raw`$32$`, String.raw`$36$`, String.raw`$48$`, String.raw`$54$`],
        answer: 1,
        explanation: [
          String.raw`The perimeters are in the same ratio as corresponding sides, so the scale factor from $ABC$ to $DEF$ is $\frac{16}{24} = \frac{2}{3}$.`,
          String.raw`Areas scale by the square of the scale factor: $72 \cdot \frac{4}{9} = 32$.`,
          String.raw`The wrong answer $48$ comes from scaling the area by $\frac{2}{3}$ instead of $\frac{4}{9}$.`,
        ],
      },
      {
        id: "z-13-14-15",
        type: "mc1",
        difficulty: "hard",
        stem: String.raw`A triangle has sides of lengths $13$, $14$ and $15$. What is the length of the height from the opposite vertex to the side of length $14$?`,
        choices: [String.raw`$10$`, String.raw`$11$`, String.raw`$12$`, String.raw`$12.5$`, String.raw`$13$`],
        answer: 2,
        explanation: [
          String.raw`Drop the height $h$ to the side of length $14$. It splits that side into $x$ and $14 - x$, and forms two right triangles, with hypotenuses $13$ and $15$.`,
          String.raw`$x^2 + h^2 = 169$ and $(14 - x)^2 + h^2 = 225$. Subtracting: $196 - 28x = 56$, so $x = 5$, and then $h^2 = 169 - 25 = 144$, so $h = 12$.`,
          String.raw`The two right triangles are $5$-$12$-$13$ and $9$-$12$-$15$ (since $14 - 5 = 9$), both Pythagorean triples. The foot of the height lies inside the side, since $0 < 5 < 14$. As a check, the area is $\frac{1}{2}(14)(12) = 84$.`,
        ],
      },
      {
        id: "z-isosceles-40",
        type: "mcm",
        difficulty: "medium",
        stem: String.raw`An isosceles triangle has an angle that measures $40^\circ$. Indicate all of the following that could be the measure of another angle of the triangle.`,
        choices: [String.raw`$40^\circ$`, String.raw`$50^\circ$`, String.raw`$70^\circ$`, String.raw`$90^\circ$`, String.raw`$100^\circ$`, String.raw`$140^\circ$`],
        answer: [0, 2, 4],
        explanation: [
          String.raw`Equal sides have equal opposite angles, so an isosceles triangle has two equal angles. The given $40^\circ$ is either one of the two equal angles or the odd one.`,
          String.raw`If $40^\circ$ is one of the equal angles, the angles are $40, 40, 100$ (the others are $40$ and $100$).`,
          String.raw`If $40^\circ$ is the odd angle, the equal angles are $\frac{180 - 40}{2} = 70$ each: $40, 70, 70$ (the others are $70$ and $70$).`,
          String.raw`So the possible measures for another angle are $40$, $70$ and $100$. The values $50$ and $90$ would give the scalene triangle $40, 50, 90$, and $140$ would leave $0^\circ$ for the third angle.`,
        ],
      },
      {
        id: "z-congruence",
        type: "mcm",
        difficulty: "hard",
        stem: String.raw`In triangles $ABC$ and $DEF$, $AB = DE$ and the measure of angle $A$ equals the measure of angle $D$. Indicate all of the following additional conditions that, together with these, guarantee that triangles $ABC$ and $DEF$ are congruent.`,
        choices: [
          String.raw`$AC = DF$`,
          String.raw`$BC = EF$`,
          String.raw`The measure of angle $B$ equals the measure of angle $E$`,
          String.raw`The measure of angle $C$ equals the measure of angle $F$`,
          String.raw`The measure of angle $B$ equals the measure of angle $F$`,
        ],
        answer: [0, 2, 3],
        explanation: [
          String.raw`The correspondence from the letters is $A \leftrightarrow D$, $B \leftrightarrow E$, $C \leftrightarrow F$.`,
          String.raw`$AC = DF$: two sides ($AB$, $AC$) and the included angle $A$, so SAS. Yes.`,
          String.raw`Angle $B$ = angle $E$: angles $A$ and $B$ with the included side $AB$, so ASA. Yes.`,
          String.raw`Angle $C$ = angle $F$: angles $A$ and $C$ with side $AB$, which is not between them, so AAS. Yes.`,
          String.raw`$BC = EF$: this is a side that is not between the given angle and side (SSA), which does not guarantee congruence. No.`,
          String.raw`Angle $B$ = angle $F$: $B$ and $F$ are not corresponding angles, so this tells us nothing. No.`,
        ],
      },
      {
        id: "z-nested-area",
        type: "ne",
        difficulty: "medium",
        diagram: { key: "3-3-triangles/nested", props: { variant: "example" }, caption: NTS },
        stem: String.raw`In the figure, $D$ is on $AB$ and $E$ is on $AC$, with $DE$ parallel to $BC$, $AD = 4$ and $DB = 6$. The area of triangle $ABC$ is $50$. What is the area of quadrilateral $DBCE$?`,
        answer: { kind: "decimal", value: "42" },
        explanation: [
          String.raw`Since $DE$ is parallel to $BC$, triangles $ADE$ and $ABC$ are similar (they share angle $A$, and the other angles are corresponding angles of parallel lines).`,
          String.raw`The scale factor compares $AD$ with the whole $AB$: $\frac{4}{4 + 6} = \frac{2}{5}$, not $\frac{4}{6}$.`,
          String.raw`Area of $ADE = 50 \cdot \left(\frac{2}{5}\right)^2 = 50 \cdot \frac{4}{25} = 8$.`,
          String.raw`The quadrilateral is the rest: $50 - 8 = 42$.`,
        ],
      },
      {
        id: "z-hypotenuse-height",
        type: "ne",
        difficulty: "hard",
        stem: String.raw`The legs of a right triangle have lengths $15$ and $20$. What is the length of the height from the right angle to the hypotenuse?`,
        answer: { kind: "decimal", value: "12" },
        explanation: [
          String.raw`The hypotenuse is $\sqrt{15^2 + 20^2} = \sqrt{625} = 25$ (a $3$-$4$-$5$ triple times $5$).`,
          String.raw`Compute the area using the legs as base and height: $\frac{1}{2}(15)(20) = 150$.`,
          String.raw`Compute it again with the hypotenuse as the base: $\frac{1}{2}(25)h = 150$, so $h = \frac{300}{25} = 12$.`,
          String.raw`Both base-and-height pairs describe the same triangle, so they give the same area.`,
        ],
      },
    ],
  },
};

export default section;
