// Generated by scripts/register.ts — do not edit by hand.
import type { Section } from "../types";
import s_3_5_circles from "./3-5-circles";

export const SECTIONS: Record<string, Section> = {
  "3-5-circles": s_3_5_circles,
};
