// Generated by scripts/register.ts — do not edit by hand.
import type { Section } from "../types";
import s_1_1_integers from "./1-1-integers";
import s_1_2_fractions from "./1-2-fractions";
import s_1_3_exponents_and_roots from "./1-3-exponents-and-roots";
import s_1_4_decimals from "./1-4-decimals";
import s_1_5_real_numbers from "./1-5-real-numbers";
import s_1_6_ratio from "./1-6-ratio";
import s_1_7_percent from "./1-7-percent";
import s_2_1_algebraic_expressions from "./2-1-algebraic-expressions";
import s_2_2_rules_of_exponents from "./2-2-rules-of-exponents";
import s_2_3_linear_equations from "./2-3-linear-equations";
import s_2_4_quadratic_equations from "./2-4-quadratic-equations";
import s_2_5_linear_inequalities from "./2-5-linear-inequalities";
import s_2_6_functions from "./2-6-functions";
import s_2_7_applications from "./2-7-applications";
import s_2_8_coordinate_geometry from "./2-8-coordinate-geometry";
import s_2_9_graphs_of_functions from "./2-9-graphs-of-functions";
import s_3_1_lines_and_angles from "./3-1-lines-and-angles";
import s_3_2_polygons from "./3-2-polygons";
import s_3_3_triangles from "./3-3-triangles";
import s_3_4_quadrilaterals from "./3-4-quadrilaterals";
import s_3_5_circles from "./3-5-circles";
import s_3_6_three_dimensional_figures from "./3-6-three-dimensional-figures";
import s_4_1_presenting_data from "./4-1-presenting-data";
import s_4_2_describing_data from "./4-2-describing-data";
import s_4_3_counting_methods from "./4-3-counting-methods";
import s_4_4_probability from "./4-4-probability";
import s_4_5_distributions from "./4-5-distributions";

export const SECTIONS: Record<string, Section> = {
  "1-1-integers": s_1_1_integers,
  "1-2-fractions": s_1_2_fractions,
  "1-3-exponents-and-roots": s_1_3_exponents_and_roots,
  "1-4-decimals": s_1_4_decimals,
  "1-5-real-numbers": s_1_5_real_numbers,
  "1-6-ratio": s_1_6_ratio,
  "1-7-percent": s_1_7_percent,
  "2-1-algebraic-expressions": s_2_1_algebraic_expressions,
  "2-2-rules-of-exponents": s_2_2_rules_of_exponents,
  "2-3-linear-equations": s_2_3_linear_equations,
  "2-4-quadratic-equations": s_2_4_quadratic_equations,
  "2-5-linear-inequalities": s_2_5_linear_inequalities,
  "2-6-functions": s_2_6_functions,
  "2-7-applications": s_2_7_applications,
  "2-8-coordinate-geometry": s_2_8_coordinate_geometry,
  "2-9-graphs-of-functions": s_2_9_graphs_of_functions,
  "3-1-lines-and-angles": s_3_1_lines_and_angles,
  "3-2-polygons": s_3_2_polygons,
  "3-3-triangles": s_3_3_triangles,
  "3-4-quadrilaterals": s_3_4_quadrilaterals,
  "3-5-circles": s_3_5_circles,
  "3-6-three-dimensional-figures": s_3_6_three_dimensional_figures,
  "4-1-presenting-data": s_4_1_presenting_data,
  "4-2-describing-data": s_4_2_describing_data,
  "4-3-counting-methods": s_4_3_counting_methods,
  "4-4-probability": s_4_4_probability,
  "4-5-distributions": s_4_5_distributions,
};
