// Generated by scripts/register.ts — do not edit by hand.
import type { Section } from "../types";
import s_1_1_integers from "./1-1-integers";
import s_1_2_fractions from "./1-2-fractions";
import s_1_3_exponents_and_roots from "./1-3-exponents-and-roots";
import s_1_4_decimals from "./1-4-decimals";
import s_1_5_real_numbers from "./1-5-real-numbers";
import s_1_6_ratio from "./1-6-ratio";
import s_1_7_percent from "./1-7-percent";
import s_2_2_rules_of_exponents from "./2-2-rules-of-exponents";
import s_2_7_applications from "./2-7-applications";
import s_3_5_circles from "./3-5-circles";

export const SECTIONS: Record<string, Section> = {
  "1-1-integers": s_1_1_integers,
  "1-2-fractions": s_1_2_fractions,
  "1-3-exponents-and-roots": s_1_3_exponents_and_roots,
  "1-4-decimals": s_1_4_decimals,
  "1-5-real-numbers": s_1_5_real_numbers,
  "1-6-ratio": s_1_6_ratio,
  "1-7-percent": s_1_7_percent,
  "2-2-rules-of-exponents": s_2_2_rules_of_exponents,
  "2-7-applications": s_2_7_applications,
  "3-5-circles": s_3_5_circles,
};
